version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: monty-postgres
    environment:
      POSTGRES_DB: monty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monty-network

  redis:
    image: redis:7-alpine
    container_name: monty-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monty-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: monty-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - monty-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  monty-network:
    driver: bridge